modLoader="lowcodefml"
loaderVersion="[1,)"
license="Unlicense"

[[mods]]
modId="default_skill_trees"
version="1.0"
displayName="Default Skill Trees"
description="Adds default skill trees for Pufferfish's Skills mod."
authors="Pufferfish"
